### PR TITLE
Notify via Slack if the deployment fails

### PR DESCRIPTION
**Pull request by whi-tw**
What
----

Send a slack notification if the build fails.

How to review
-------------

Code review

Who can review
--------------

Not me

### CODE REVIEW

**Comment by kr8n3r** [comment]
is there a reason we're using this and not Slack's own GH action?

**Comment by AP-Hunt** [comment]
Agree with Jani. If we can use Slack's official thing then I think we ought to.

**Comment by whi-tw** [comment]
@AP-Hunt @kr8n3r This action 'just works', rather than Slack's, which involves setting up all the custom message blocks.

To me, there doesn't seem to be a whole load of point in attempting to replicate the functionality of this action, having to learn the Slack message API, when there's an action which does specifically what we need.

Happy to put the time into changing the implementation if that is really what we want, though.

**Comment by kr8n3r** [comment]
you should be able to just do 
`payload: "{"text": "Deployment of ${{ github.event.pull_request.html_url }} FAILED"}"`

**Comment by cadmiumcat** [comment]
When you say "Slack's own thing", do you mean https://github.com/marketplace/actions/slack-send ? 
If it's as simple as @kr8n3r suggested, then I agree we ought to change it

**Comment by AP-Hunt** [comment]
I would like us to use the Slack official action, please. I know it's a little rework, sorry.

**Review by AP-Hunt — DISMISSED** [review]
See comment

**Review by kr8n3r — APPROVED** [review]
looks good. we'll see if it works

**Review by AP-Hunt — APPROVED** [review]

**Pull request merged**
