### PR TITLE
[#183708862] Use Ruby 3.1.0

### PR DESCRIPTION
**Pull request by AP-Hunt**
What
----
Upgrades to Ruby 3.1.0 to be consistent with the rest of our estate

How to review
-------------

1. Checks pass
2. `bundle exec middleman`

Who can review
--------------
@kr8n3r would be valuable

### CODE REVIEW

**Comment by kr8n3r** [comment]
@AP-Hunt this is unlikely going to work as work most likely needs to be done upstream in the tech-docs-gem  (if packages actually support ruby 3)

**Comment by AP-Hunt** [comment]
Bugger. I ran `bundle exec middleman` locally and it worked. Maybe `rbenv` had me using the wrong Ruby version.

**Comment by kr8n3r** [comment]
https://github.com/gjtorikian/html-proofer/issues/781 error given is fixed in v5 but v5 is not available in GH actions

**Comment by AP-Hunt** [comment]
Maybe we can check back in on this in a week or two? Looks like those whole thing is still active.

**Comment by kr8n3r** [comment]
@AP-Hunt all fixed. Can you review changes and squash commits if happy?

**Comment by AP-Hunt** [comment]
I can't review because I opened the PR, but I'm happy with what's there. I don't think the commits need squashing either, they make sense in isolation.

**Review by kr8n3r — APPROVED** [review]

**Pull request merged**
