### PR TITLE
[#136558969] Add IPSec debugging guide

### PR DESCRIPTION
**Pull request by paroxp**
## What

We're about to implement the IPSec encryption, between some of our nodes. It may so happen, that one will be in need of debugging the IPSec connectivity. Wrong time in the wrong place, I suppose.

In order to make their task simpler, we'd like to document some of the techniques we've used while implementing the IPSec.

## How to review

Read through the docs and see if these make any sense...

## Who can review

Not @mtekel or @paroxp

### CODE REVIEW

**Comment by Jonty** [comment]
Fixed some minor typos, other than that A+ would debug ipsec again.

**Comment by combor** [comment]
It might be worth to add `tcpdump -i eth0 -n -s 0 -vv \(port 500 or port 4500 or proto 50\)` command to the guide. It allows you to capture IPSEC only. I found lit quite useful.

**Comment by combor** [comment]
Oh, my...too late.

**Comment by mtekel** [comment]
If you open a small PR to do that I can merge quickly as I have used that command, so I have reviewed it works...

**Comment by combor** [comment]
@mtekel here you go https://github.com/alphagov/paas-team-manual/pull/87

**Pull request merged**
