### PR TITLE
[#136558969] Add a tcpdump command that filters IPSEC

### PR DESCRIPTION
**Pull request by combor**
### What

Follow up to discussion https://github.com/alphagov/paas-team-manual/pull/84#issuecomment-271840064 
I found this command quite useful when debugging IPSEC so let's add it to the team manual.

### Who

Not @combor

### CODE REVIEW

**Comment by paroxp** [comment]
Could you also fix the link to the FreeBSD docs?

**Comment by paroxp** [comment]
^ Just for context, see: https://government-paas-team-manual.readthedocs.io/en/latest/guides/IPSec_debugging/#verifying-configuration

**Comment by mtekel** [comment]
IMO it's best that you commit @paroxp . I can still merge that...

**Comment by combor** [comment]
@paroxp I'm not sure what you want to fix?

**Comment by mtekel** [comment]
ok, that's enough, let's leave more fixes for another PR

**Comment by combor** [comment]
We had personal chat about it and we've made FreeBDS manual link clickable.

**Pull request merged**
