### PR TITLE
Guidance for learning about tech we use

### PR DESCRIPTION
**Pull request by bleach**
**Please do not merge** - this is incomplete change. I'm hoping for corrections, discussion and contributions to fill the blanks.

Create a list of things that will help a new starter to the team learn about
the tech we use. Written for someone who has experience running infrastructure,
but hasn't used the particular tools we use. (eg. me)

Since markdown tables are pretty horrid to read in plain text, you'll likely want to click on "Files changed", then View to see rendered markdown.

### CODE REVIEW

**Comment by dcarley** [comment]
I had been meaning to add a link to the presentation slides that @saliceti and @actionjack gave. This seems like a good place. Does everyone think that it's still relevant in a Diego-world and useful without the spoken content?

**Comment by timmow** [comment]
@dcarley I found the presentation really useful when I started the team, and I think its still fairly relevant in a post diego world

**Comment by bleach** [comment]
OK, I think this is ready to be merged.

**Comment by bleach** [comment]
I've linked both the old presentation and the new one post-diego. Also, I added links terraform and BOSH guides.

**Comment by dcarley** [comment]
Going to end the 25 day streak on our PR dashboard :metal:

**Pull request merged**
